# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lunchclub.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('amount', lunchclub.fields.AmountField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('balance', lunchclub.fields.AmountField(decimal_places=2, max_digits=19)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lunchclub.Person'),
        ),
        migrations.AddField(
            model_name='expense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunchclub.Person'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lunchclub.Person'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunchclub.Person'),
        ),
    ]
