# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0002_shoppinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('yes', 'I want lunchclub lunch'), ('own', 'I bring my own lunch'), ('no', 'I have other plans')], max_length=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunchclub.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set([('date', 'person')]),
        ),
    ]
