# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0003_create_rsvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('who', 'Initiate protocol!'), ('way', 'Tell all someone is getting food'), ('now', "Tell all there's lunch now")], max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunchclub.Person')),
            ],
        ),
    ]
