# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import lunchclub.models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0004_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[lunchclub.models.username_validate]),
        ),
    ]
