# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:29
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def set_display_name(apps, schema_editor):
    Person = apps.get_model('lunchclub', 'Person')
    Person.objects.filter(display_name__isnull=True).update(
        display_name=F('username'))


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0005_person_name'),
    ]

    operations = [
        migrations.RunPython(set_display_name),
    ]
