# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0006_set_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
