# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0007_display_name_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
