# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0008_rsvp_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hide_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
