# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-09 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0009_person_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date', 'person', 'created_by']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date', 'person', 'amount']},
        ),
    ]
